config/routes.rb
Rails.application.routes.draw do
  # ここはdeviseのルーティング
  # 会員用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  # エラーメッセージ後のリロード対策
   devise_scope :user do
    get '/users', to: 'public/registrations#new'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # ここからは通常のルーティング
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'

  get 'public/ranks/cute_rank'
  get 'public/ranks/look_rank'

  # 退会確認画面
  get 'public/users/:id/unsubscribe' => 'public/users#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch 'public/users/:id/withdrawal' => 'public/users#withdrawal', as: 'withdrawal'

  #MAP用
  get 'admin/posts/map'
  get 'public/posts/map'


  # 管理者側
  namespace :admin do
    resources :homes, only: [:top]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    # genresのnew,showを除くルーティング自動生成
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :show, :edit, :update]
  end

  # 会員側
  # namespace :public do
  scope module: :public do
    resources :homes, only: [:top, :about] # %i(top about)
    resources :genres, only: [:index]
    get 'posts/my_index' => 'posts#my_index', as: 'my_index'
    resources :posts do

      # 見た、かわいいボタン用
      resources :looks, only: [:create, :destroy]
      resources :cutes, only: [:create, :destroy]
      resources :contacts, only: [:new, :create]
      member do
        get :cutes
        get :looks
      end
      # コメント用
      resources :comments, only: [:create, :destroy]
    end
    resources :users, except: [:index, :show] do
      # フォロー、フォロワー用
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'public/relationships#followings', as: 'followings'
      get 'followers' => 'public/relationships#followers', as: 'followers'
    end
    # お問合せ用
    resources :contacts, only: [:new, :create]
    # 検索用
    get "search" => "searches#search_result"
    # ソート用
    get 'sort' => 'posts#sort_index'
    # get 'users' => 'users#show', as: 'show'
    get 'users/:id' => 'users#edit', as: 'get_update'

    get 'infos/hogo' => 'infos#hogo', as: 'hogo'
    get 'infos/nora' => 'infos#nora', as: 'nora'
    end

  # ルーティングがマッチしないため
  namespace :public do
    get 'users' => 'users#show', as: 'show'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :image

  has_many :comments,   dependent: :destroy
  has_many :cutes,      dependent: :destroy
  has_many :looks,      dependent: :destroy
  
  # フォロー関係
  # has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  # has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  
  # 一覧画面
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  
  # 名前のバリデーション※15文字まで 他のニックネームと被らないように
  validates :name, presence: true, length: { minimum: 2,maximum: 15 }, uniqueness: true
  
  # 絞り込みのためのスコープ 退会済を弾く
  scope :narrow_down, -> { where.not(user_id: User.where(is_deleted: true).ids) }

  # 退会したユーザーがログインできないように
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  # ゲストユーザー
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
    end
  end

  # フォロー関連の記述
  # # フォローしたときの処理
  # def follow(user_id)
  #   relationships.create(followed_id: user_id)
  # end
  # # フォローを外すときの処理
  # def unfollow(user_id)
  #   relationships.find_by(followed_id: user_id).destroy
  # end
  # # フォローしているか判定
  # def following?(user)
  #   followings.include?(user)
  # end

  # User画像のないときの処理
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg')
    end
    image
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_user, only: [:show,:edit,:update]

  def index
    # ページネーション追加
    @users = User.all.page(params[:page]).per(10)
  end

  def show
  end

  def edit
  end

  def update
    @user.update(user_params)
    flash[:notice] = "更新しました。"
    redirect_to admin_user_path(@user.id)
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :is_deleted)
  end

  def set_user
     @user = User.find(params[:id])
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3" style="text-align: center; margin-top: 50px;">
      <h2>User Edit</h2>
    </div>
    <div class="col-md-6" style="margin-top: 50px;">
      <%= form_with model: [:admin, @user] do |f| %>
      <table class="table table-inverse">
        <tr>
          <th>プロフィールアイコン</th>
          <td><%= image_tag @user.get_image, class: "rounded-circle", size: "150x150" %></td>
        </tr>
        <tr>
          <th>ユーザーID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <td><%= f.label :会員ステータス %></td>
          <td>
            <%= f.radio_button :is_deleted, :false %>
            <%= f.label :is_deleted, "有効", value: false %>
            <%= f.radio_button :is_deleted, :true %>
            <%= f.label :is_deleted, "退会", value: true %>
          </td>
        </tr>
        <tr>
          <td><%= f.submit "変更を保存", class: 'btn btn-success' %></td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-5" style="text-align: center;">
      <h2>User's</h2>
    </div>
    <div class="col-md-6" style="text-align: center; margin-top: 50px;">
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th>ユーザーID</th>
            <th>プロフィールアイコン</th>
            <th>ニックネーム</th>
            <th>メールアドレス</th>
            <th>登録日</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.id %></td>
            <td><%= image_tag user.get_image,class: "rounded-circle", size: "50x50" %></td>
            <td><%= link_to user.name, admin_user_path(user.id) %></td>
            <td><%= user.email %></td>
            <td class="day"><%= l user.created_at, format: :short %></td>
            <% if user.is_deleted == false %>
              <td>有効</td>
            <% else %>
              <td>退会</td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <div class="pagination" style="justify-content: center; margin-top: 30px;">
       <!--ページネーション入れる-->
      <p><%= paginate @users %></p>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-3 mt-5" style="text-align: center;">
      <h2>User Details</h2>
    </div>
    <div class="col-md-6" style="margin-top: 50px; text-align: center;">
      <table  class="table table-inverse">
        <tr>
          <th>プロフィールアイコン</th>
          <td><%= image_tag @user.get_image,class: "rounded-circle", size: "150x150" %></td>
        </tr>
        <tr>
          <th>ユーザーID</th>
          <td><%= @user.id %></td>
        </tr>
        <tr>
          <th>ニックネーム</th>
          <td><%= @user.name %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @user.email %></td>
        </tr>
        <tr>
          <th>登録日</th>
          <td><%= l @user.created_at, format: :short %></td>
        </tr>
        <tr>
          <th>ユーザーステータス</th>
          <!--ステータスの記述を行う。-->
          <td><%= user_status(@user) %></td>
        </tr>
      </table>
      <div style="text-align: center; margin-top: 50px;">
        <p><%= link_to "編集", edit_admin_user_path(@user), class: 'btn btn-success' %></p><br>
        <p><%= link_to "ユーザー一覧", admin_users_path, class: 'btn btn-primary' %></p>
      </div>
    </div>
  </div>
</div>