config/routes.rb
Rails.application.routes.draw do
  # ここはdeviseのルーティング
  # 会員用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  # エラーメッセージ後のリロード対策
   devise_scope :user do
    get '/users', to: 'public/registrations#new'
  end

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  # ゲストログイン用
  devise_scope :user do
    post 'users/guest_sign_in', to: 'public/sessions#guest_sign_in'
  end

  # ここからは通常のルーティング
  root to: 'public/homes#top'
  get 'public/homes/about' => 'public/homes#about', as: 'about'

  get 'public/ranks/cute_rank'
  get 'public/ranks/look_rank'

  # 退会確認画面
  get 'public/users/:id/unsubscribe' => 'public/users#unsubscribe', as: 'unsubscribe'
  # 論理削除用のルーティング
  patch 'public/users/:id/withdrawal' => 'public/users#withdrawal', as: 'withdrawal'

  #MAP用
  get 'admin/posts/map'
  get 'public/posts/map'


  # 管理者側
  namespace :admin do
    resources :homes, only: [:top]
    resources :posts, only: [:index, :show, :edit, :update, :destroy]
    # genresのnew,showを除くルーティング自動生成
    resources :genres, except: [:new, :show]
    resources :users, only: [:index, :show, :edit, :update]
  end

  # 会員側
  # namespace :public do
  scope module: :public do
    resources :homes, only: [:top, :about] # %i(top about)
    resources :genres, only: [:index]
    get 'posts/my_index' => 'posts#my_index', as: 'my_index'
    resources :posts do

      # 見た、かわいいボタン用
      resources :looks, only: [:create, :destroy]
      resources :cutes, only: [:create, :destroy]
      resources :contacts, only: [:new, :create]
      member do
        get :cutes
        get :looks
      end
      # コメント用
      resources :comments, only: [:create, :destroy]
    end
    resources :users, except: [:index, :show] do
      # フォロー、フォロワー用
      resource :relationships, only: [:create, :destroy]
      get 'followings' => 'public/relationships#followings', as: 'followings'
      get 'followers' => 'public/relationships#followers', as: 'followers'
    end
    # お問合せ用
    resources :contacts, only: [:new, :create]
    # 検索用
    get "search" => "searches#search_result"
    # ソート用
    get 'sort' => 'posts#sort_index'
    # get 'users' => 'users#show', as: 'show'
    get 'users/:id' => 'users#edit', as: 'get_update'

    get 'infos/hogo' => 'infos#hogo', as: 'hogo'
    get 'infos/nora' => 'infos#nora', as: 'nora'
    end

  # ルーティングがマッチしないため
  namespace :public do
    get 'users' => 'users#show', as: 'show'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.erb
<% if model.errors.any? %>
  <div class="alert alert-danger">
    <ul class="list-unstyled">
      <h5><%= model.errors.count %>件のエラー</h5>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<!-- footerの部分テンプレート -->
<footer class="footer fixed-bottom" style="background-color: #d6c6af;">
  <div class="container p-2">
    <div class="row">
      <div class="col-lg-3">
        <h4 style="font-family: Caveat;">Link</h6>
        <!-- ユーザーがログインしている＆会員の場合に表示 -->
        <ul class="p-0 list-unstyled">
        <% if user_signed_in? %>
        <li><%= link_to "野良猫の接し方", nora_path %></li>
        <li><%= link_to "迷い猫の保護の仕方", hogo_path %></li>
        <li><%= link_to "お問合せ",new_contact_path( user_id: current_user.id ) %></li>
        <!-- ユーザーがログインしているかつ管理者の場合に表示 -->
        <% elsif admin_signed_in? %>
          <li>管理者ログイン中</li>
        <!-- 未ログインの場合に表示 -->
        <% else %>
          <li><%= link_to "野良猫の接し方", nora_path %></li>
          <li><%= link_to "迷い猫の保護の仕方", hogo_path %></li>
          <li><%= link_to "管理者入口", new_admin_session_path %></li>
        <% end %>
        </ul>
      </div>
      <div class="col-md-8" style="text-align: center; padding-top: 50px;">
        <h4 style="font-family: Caveat;"> ©︎2022 Stray Cat's MAP.inc</h4>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<!-- headerの部分テンプレート -->
<header>
  <!-- ナビゲーションバーのレイアウト -->
  <nav class ="navbar fixed-top navbar-expand-lg navbar-light" style="background-color: #d6c6af;">
    <div class="container-fluid">
      <!-- 店名ロゴの表示-->
      <a class="navbar-brand" href="/" style="font-family: Caveat;">
        <span><i class="fa-solid fa-paw"style="margin-right: 5px;"></i>Stray Cat's MAP<i class="fa-solid fa-paw"style="margin-left: 5px;"></i></span><br>
        <span class="ttl_read">この世界にはたくさんの猫たちがいます。さぁ一緒に探しに行きませんか？</span>
      </a>
      <div class="ml-5"><%= render "public/searches/search" %></div>
      <!-- ナビゲーション要素の追加 -->
      <button class="navbar-toggler" type="button" data-toggle="collapse"
        data-target="#navbarNavDropdown"
        aria-controls="navbarNavDrapdown"
        aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <!-- ユーザーがログインしている＆会員の場合に表示 -->
          <% if user_signed_in? %>
            <li>
              <!--現在ログインしているユーザーのマイページ。-->
              <%= link_to public_show_path, class: 'nav-link text-dark' do %>
                <i class="fa-regular fa-user"></i>
                  My Page
              <% end %>
            </li>
            <li>
              <%= link_to  public_posts_map_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-map-location-dot"></i>
                  MAP
              <% end %>
            </li>
            <li>
              <!--postのページだけturbolinksを切る-->
              <%= link_to  new_post_path, class: 'nav-link text-dark',data: {"turbolinks"=>false} do %>
                <i class="fa-solid fa-paper-plane"></i>
                  Post
              <% end %>
            </li>
            <li>
              <%= link_to posts_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-cat"></i>
                  Cat's
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark', id: 'logout_link' do %>
                <i class="fas fa-sign-out-alt"></i>
                  Log out
              <% end %>
            </li>
            <!-- ユーザーがログインしているかつ管理者の場合に表示 -->
          <% elsif admin_signed_in? %>
            <li>
              <%= link_to admin_users_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-users"></i>
                  User's
              <% end %>
            </li>
            <li>
              <%= link_to admin_posts_map_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-map-location-dot"></i>
                  MAP
              <% end %>
            </li>
            <li>
              <%= link_to admin_genres_path, class: 'nav-link text-dark' do %>
              <i class="fa-solid fa-tags"></i>
                  Genre's
              <% end %>
            </li>
            <li>
              <%= link_to admin_posts_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-cat"></i>
                  Cat's
              <% end %>
            </li>
            <li>
              <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-right-from-bracket"></i>
                  Log out
              <% end %>
            </li>
          <!-- 未ログインの場合に表示 -->
          <% else %>
            <li>
              <%= link_to about_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-fish"></i>
                  About
              <% end %>
            </li>
            <li>
              <%= link_to public_posts_map_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-map-location-dot" style="margin-right: 5px;"></i>
                  MAP
              <% end %>
            </li>
            <li>
              <%= link_to posts_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-cat"></i>
                  Cat's
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-right-to-bracket" style="margin-right: 5px;"></i>
                  Log in
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
                <i class="fa-solid fa-house-chimney" style="margin-right: 5px;"></i>
                  Sign up
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <!--フラッシュメッセージ用-->
  <% if notice || alert %>
    <div class="alert alert-secondary">
      <div class="container">
        <%= notice %>
        <%= alert %>
        <button type="button" class="close"
      data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stray Cat's MAP</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel ="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <!--アラート用にptを入れる-->
    <!--@topでtop画面にだけの背景画像-->
    <div class="background<%=@top%>">
      <div class="pt-5">
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>